# Generated by Django 3.2.5 on 2021-07-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('d1', 'Departamento 1'), ('d2', 'Departamento2'), ('d3', 'Departamento3')], max_length=2)),
            ],
        ),
    ]
