# Generated by Django 3.0.8 on 2021-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('passwd', models.TextField()),
            ],
            options={
                'db_table': 'useraccess',
            },
        ),
    ]
